### ISSUE TITLE
A request for a full target sequence list used in 89 libraries

### ISSUE THREAD

**Issue by CrazyHsu** [ltschmitt/RecGen#2]
Hi, thank you for developing such a great tool. As metioned in #1 , some positions in nucleotide sequences are masked with asterisks *. For a better usage experience, can you provide a complete target sequences used in 89 libraries? Thans you in advance!

**Comment by ltschmitt** [comment]
Hi, please write the corresponding author regarding the data. This repository is only for storing the code.
